"""
Example usage of PostgreSQL Logger

This file demonstrates how to use the PG Logger utility to connect 
to PostgreSQL and insert logs.
"""

import frappe
from datahubv2.lib.pg_connect import PGLogger, log_to_postgres, log_before_after_to_postgres


def example_basic_logging():
    """Example of basic logging to PostgreSQL"""
    
    # Method 1: Using convenience function
    success = log_to_postgres(
        ref_id="98765",
        ref_module="order",
        json_data={
            "before": {"status": "pending", "amount": 1500},
            "after": {"status": "paid", "amount": 1500}
        }
    )
    
    print(f"Log insertion successful: {success}")


def example_before_after_logging():
    """Example of before/after logging to PostgreSQL"""
    
    # Method 2: Using before/after convenience function
    success = log_before_after_to_postgres(
        ref_id="98765",
        ref_module="order",
        before_data={"status": "pending", "amount": 1500},
        after_data={"status": "paid", "amount": 1500}
    )
    
    print(f"Before/After log insertion successful: {success}")


def example_using_logger_class():
    """Example using PGLogger class directly"""
    
    # Method 3: Using PGLogger class directly
    logger = PGLogger()
    
    # Create table if not exists (optional, will be created automatically)
    logger.create_log_table_if_not_exists()
    
    # Insert a log
    success = logger.insert_log(
        ref_id="12345",
        ref_module="customer",
        json_data={
            "action": "update_profile",
            "changes": {
                "email": {
                    "from": "old@example.com",
                    "to": "new@example.com"
                },
                "phone": {
                    "from": "+66812345678",
                    "to": "+66887654321"
                }
            },
            "timestamp": "2025-01-01T10:00:00Z"
        }
    )
    
    print(f"Complex log insertion successful: {success}")


def example_retrieve_logs():
    """Example of retrieving logs from PostgreSQL"""
    
    logger = PGLogger()
    
    # Get all logs
    all_logs = logger.get_logs(limit=10)
    print(f"Retrieved {len(all_logs)} logs")
    
    # Get logs by ref_id
    ref_logs = logger.get_logs(ref_id="98765", limit=5)
    print(f"Retrieved {len(ref_logs)} logs for ref_id 98765")
    
    # Get logs by module
    module_logs = logger.get_logs(ref_module="order", limit=5)
    print(f"Retrieved {len(module_logs)} logs for order module")


def example_in_frappe_context():
    """Example of using in Frappe context (like in a hook or API)"""
    
    # This would typically be used in Frappe hooks like:
    # - on_update
    # - after_insert
    # - before_save
    # etc.
    
    try:
        # Simulate some business logic
        order_id = "ORD-2025-001"
        
        # Log the action
        success = log_before_after_to_postgres(
            ref_id=order_id,
            ref_module="sales_order",
            before_data={
                "status": "draft",
                "total_amount": 5000,
                "items_count": 3
            },
            after_data={
                "status": "submitted",
                "total_amount": 5000,
                "items_count": 3,
                "submitted_by": frappe.session.user,
                "submitted_at": frappe.utils.now()
            }
        )
        
        if success:
            frappe.logger().info(f"Successfully logged order submission for {order_id}")
        else:
            frappe.log_error(f"Failed to log order submission for {order_id}", "Order Log Error")
            
    except Exception as e:
        frappe.log_error(f"Error in order logging: {str(e)}", "Order Log Exception")


# Example SQL that would be generated:
"""
-- Table creation (auto-generated)
CREATE TABLE IF NOT EXISTS my_data_log (
    id SERIAL PRIMARY KEY,
    ref_id VARCHAR(255) NOT NULL,
    ref_module VARCHAR(255) NOT NULL,
    json_data JSONB,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Example insert (auto-generated by the code above)
INSERT INTO my_data_log (ref_id, ref_module, json_data)
VALUES (
  '98765',
  'order',
  '{"before": {"status": "pending", "amount": 1500}, "after": {"status": "paid", "amount": 1500}}'::jsonb
);
"""


if __name__ == "__main__":
    # Run examples (uncomment as needed)
    # example_basic_logging()
    # example_before_after_logging()
    # example_using_logger_class()
    # example_retrieve_logs()
    # example_in_frappe_context()
    pass